remove/extract Coc, fix import of lua scripts, use nvimlsp

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,3 +16,11 @@ then
     sudo npm install -g git-split-diffs
     git config --global core.pager "git-split-diffs --color | less -RFX"
 fi
+
+if ! command -v pyright  &> /dev/null
+then
+    echo "The pyright npm module is missing globally, it's needed for nvim lsp"
+    sudo npm install -g pyright
+fi
+
+
